core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("main.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [

	path("", views.IndexView, name="index"),
	path("auction/", views.AuctionView, name="auction"),
	path("account/", views.AccountView, name="account"),
	path("checkout/", views.CheckOutView, name="checkout"),

	path("find/", views.FindView, name="find"),
	path("result/<str:domain_name>/", views.ResultView, name="result"),
	path("buy/<str:domain_name>/", views.BuyView, name="buy"),
	path("finish/", views.FinishView, name="finish"),
	path("registered/", views.RegisteredView, name="registered"),
	path("docs/", views.DocsView, name="docs"),
	path("transfer/<str:domain_name>/", views.Transfer2View, name="transfer2"),
	
	path("transfer/", views.TransferView, name="transfer"),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User

from django.core.mail import send_mail

from datetime import datetime
import datetime as dt
import requests

#from main.ray_bns import GetAddress, GetPrice



#from .forms import UserForm


def IndexView(request):

	if request.method == "POST":
		domain_name = request.POST.get("domain_name")

		return HttpResponseRedirect(reverse("main:result", args=[domain_name,]))

	else:

		context = {}
		return render(request, "main/index.html", context )


def AuctionView(request):

	if request.method == "POST":
		pass

	else:

		context = {}
		return render(request, "main/auction.html", context )


def AccountView(request):

	if request.method == "POST":
		pass

	else:

		context = {}
		return render(request, "main/account.html", context )

def CheckOutView(request):

	if request.method == "POST":
		pass

	else:

		context = {}
		return render(request, "main/checkout.html", context )




def FindView(request):

	if request.method == "POST":
		domain_name = request.POST.get("domain_name")

		return HttpResponseRedirect(reverse("main:result", args=[domain_name,]))

	else:

		context = {}
		return render(request, "main/find.html", context )



def ResultView(request, domain_name):

	if request.method == "POST":
		domain_name = request.POST.get("domain_name")

		return HttpResponseRedirect(reverse("main:result", args=[domain_name,]))

	else:
		#name_address = GetAddress(domain_name)
		#name_address = "0x0000000000000"
		name_address = requests.get("https://api.iotexchartapp.com/cns/get-address/%s/" % (domain_name)).json()["address"]
		#return HttpResponse(str(name_address))

		if name_address == "0x0000000000000000000000000000000000000000":
			available = True
		elif name_address == "0xA67f0392a9A70dEB2A0cf8Ae36017B20A8d11756":
		    available = None
		else:
			available = False
		
		#name_price = GetPrice(domain_name)
		name_price = requests.get("https://api.iotexchartapp.com/cns/get-price/%s/" % (domain_name)).json()["price"]


		context = {"domain_name": domain_name, "available": available,
		"name_price": name_price, "name_address": name_address}

		return render(request, "main/result.html", context )



def BuyView(request, domain_name):

	if request.method == "POST":
		pass

	else:
		name_price = requests.get("https://api.iotexchartapp.com/cns/get-price/%s/" % (domain_name)).json()["price"]

		context = {"name_price": name_price, "domain_name": domain_name,}
		return render(request, "main/buy.html", context )



def FinishView(request):

	if request.method == "POST":
		domain_name = request.POST.get("domain_name")

		return HttpResponseRedirect(reverse("main:result", args=[domain_name,]))

	else:

		context = {}
		return render(request, "main/finish.html", context )
		
		

def TransferView(request):
	if request.method == "POST":
		domain_name = request.POST.get("domain_name")

		return HttpResponseRedirect(reverse("main:transfer2", args=[domain_name,]))

	else:

		context = {}
		return render(request, "main/transfer.html", context )


def Transfer2View(request, domain_name):
    if request.method == "POST":
        pass

    else:

        context = {"domain_name": domain_name,}
        return render(request, "main/transfer2.html", context )	

def RegisteredView(request):
    if request.method == "POST":
        pass

    else:

        context = {}
        return render(request, "main/registered.html", context )	

def DocsView(request):

	if request.method == "POST":
		pass

	else:

		context = {}
		return render(request, "main/docs.html", context )

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/images/2.jpg' %}">
    <!-- Page title -->
    <title>Core Naming Service | Crest Protocol</title>
    
    
    <link rel="alternate icon" href="{% static 'assets/images/2.jpg' %}">
    <link rel="icon" type="image/svg+xml" href="{% static 'assets/images/2.jpg' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Crest Protocol, Metaverse, ENS, EVM, Ethereum, Name Service, Domain Names, Core Chain, NFTs, Humanizes Identities, NFT Market, AibraLabs, Young Parrot, Core Token, Ethereum Name Service, ERC721, Testnet"/>

    <meta name="msapplication-TileColor" content="#da532c"/>
    <meta name="twitter:card" content="summary_large_image"/>
    <meta property="og:title" content="Core Naming Service"/>
    <meta name="twitter:title" content="Core Naming Service"/>
    <meta name="twitter:image:width" content="400" />
    <meta name="twitter:image:height" content="300" />
    <meta name="twitter:image:src" content="{% static 'assets/images/2.jpg' %}" >

    <meta name="twitter:description" content="Official Naming Service for Core Chain, A Humanized ID for the Metaverse."/>
    <meta property="og:description" content="Official Naming Service for Core Chain, A Humanized ID for the Metaverse."/>

    
    <meta name="description" content="Official Naming Service for Core Chain, A Humanized ID for the Metaverse." content="IE=edge"/>

    <title>Core Naming Service | Crest Protocol</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/images/2.jpg' %}"/>
    
    <link rel="alternate icon" href="{% static 'assets/images/2.jpg' %}">
    <link rel="shortcut icon" href="{% static 'assets/images/2.jpg' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'assets/images/2.jpg' %}" type="image/x-icon">
    <meta name="msapplication-TileColor" content="#da532c"/>
    <meta property="og:title" content="Crest Protocol"/>
    <link rel="icon" href="{% static 'assets/images/2.jpg' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'assets/images/2.jpg' %}" type="image/x-icon">
    <title>Core Naming Service | Crest Protocol</title>
<link rel="icon" href="{% static 'assets/images/2.jpg' %}" >
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

<link rel="stylesheet" href="{% static 'assets/css/all.css' %}">

<link rel="stylesheet" href="{% static 'assets/font/flaticon.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/boxicons.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/bootstrap-icons.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/swiper.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/price-range-ui.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
</head>
<body>

<div class="preloader">
<div class="sk-cube-grid">
<div class="sk-cube sk-cube1"></div>
<div class="sk-cube sk-cube2"></div>
<div class="sk-cube sk-cube3"></div>
<div class="sk-cube sk-cube4"></div>
<div class="sk-cube sk-cube5"></div>
<div class="sk-cube sk-cube6"></div>
<div class="sk-cube sk-cube7"></div>
<div class="sk-cube sk-cube8"></div>
<div class="sk-cube sk-cube9"></div>
</div>
</div>


<a href="#" id="scroll-top" class="back-to-top-btn"><i class="fas fa-chevron-up"></i></a>


<header>

<nav>
<div class="header-menu-area">
<div class="container">
<div class="row">
<div class="col-xl-2 col-lg-2 col-sm-6 col-6">
<div class="logo text-left">
<a href="/"><img width="60%" src="{% static 'assets/images/crest001.png' %}" alt=""></a>
</div>
</div>
<div class="col-xl-7 col-lg-7 col-sm-6 col-6">
<a href="javascript:void(0)" class="hidden-lg hamburger">
<span class="h-top"></span>
<span class="h-middle"></span>
<span class="h-bottom"></span>
</a>
<nav class="main-nav">
<div class="logo mobile-ham-logo d-lg-none d-block text-left">
<a href="/"><img width="60%" src="{% static 'assets/images/crest001.png' %}" alt=""></a>
</div>
<ul>
<li class="">
<a href="/" class="active">Home</a>
</li>
<li class="has-child-menu">
<a href="javascript:void(0)">Explore</a>
<i class="fl flaticon-plus">+</i>
<ul class="sub-menu">
<li><a href="{% url 'main:registered' %}">Registered Names</a></li>
<li><a href="{% url 'main:transfer' %}">Transfer Names</a></li>

</ul>
</li>
<li class="has-child-menu">
<a href="javascript:void(0)">Documentation</a>


</li>
</ul>
<div class="menu-search-wrap d-block d-lg-none">
<form action="" class="menu-form" method="post">
  {% csrf_token %}
<a type="submit"><i class='bx bx-search'></i></a>
<input type="text" onkeyup="return forceLower(this);" name="domain_name" placeholder="Search Here">
</form>
</div>
</nav>
</div>
<div class="col-xl-3 col-lg-3 d-none d-lg-block">
<div class="menu-search-wrap">
<form action="" class="menu-form" method="post">
  {% csrf_token %}
<a type="submit"><i class='bx bx-search'></i></a>
<input type="text" onkeyup="return forceLower(this);" name="domain_name" placeholder="Search Here">
</form>

</div>
</div>
</div>
</div>
</div>
</nav>

{% block content %}

{% endblock %}

<div class="footer-area design-1">
<div class="container">
<div class="row">
<div class="col-xl-12 col-lg-12 col-sm-12 col-12">
<div class="footer-wrap">
<div class="row justify-content-between">
<div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
<div class="single-widget">
<div class="footer-logo">
<a href="/"><img width="30%" src="{% static 'assets/images/crest001.png' %}" alt=""></a>
<p>A decentralized domain naming service on core dao chain that allows users to easily discover and access decentralized services and applications.</p>
<div class="footer-social">
<ul>
<li><a href="https://twitter.com/crestprotocol_?s=21&t=1PmJM7PYRu2e096byownIA" target="_blank"><i class="fab fa-twitter"></i></a></li>
<li><a href="#"><i class="fab fa-telegram"></i></a></li>
<li><a href="#"><i class="fab fa-discord"></i></a></li>
<li><a href="#"><i class="fab fa-github"></i></a></li>
</ul>
</div>
</div>
</div>
</div>
<div class="col-xl-2 col-lg-2 col-md-6 col-sm-6 col-6">
<div class="single-widget">
<div class="footer-title">
<h4>Usefull Links</h4>
</div>
<div class="footer-link">
<ul>

<li><a href="#">Buy</a></li>
<li><a href="#">Registered Names</a></li>
<li><a href="#">Transfer Names</a></li>

</ul>
</div>
</div>
</div>
<div class="col-xl-2 col-lg-2 col-md-6 col-sm-6 col-6">
<div class="single-widget">
<div class="footer-title">
<h4>Community</h4>
</div>
<div class="footer-link">
<ul>
<li><a href="#">Help Center</a></li>
<li><a href="#">Suggestions</a></li>
<li><a href="#">Email For Collab</a></li>
</ul>
</div>
</div>
</div>
<div class="col-xl-2 col-lg-2 col-md-6 col-sm-6 col-6">
<div class="single-widget">
<div class="footer-title">
<h4>Info</h4>
</div>
<div class="footer-link">
<ul>
<li><a href="#">Documentation</a></li>
<li><a href="#">Marketplace</a></li>
<li><a href="#">Whitepaper</a></li>
<li><a href="#">Crest Protocol</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
<div class="copy-right-area text-center">
<p class="copy-text">© 2023 CrestProtocol, All Rights Reserved.</p>
</div>
</div>
</div>
</div>
</div>


<script src="{% static 'assets/js/jquery-1.12.4.min.js' %}"></script>

<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>

<script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>

<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>

<script src="{% static 'assets/js/slick.min.js' %}"></script>

<script src="{% static 'assets/js/swiper.js' %}"></script>

<script src="{% static 'assets/js/jquery.mixitup.min.js' %}"></script>

<script src="{% static 'assets/js/wow.min.js' %}"></script>

<script src="{% static 'assets/js/price-range-ui.js' %}"></script>

<script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'assets/js/counter-potnt.js' %}"></script>

<script src="{% static 'assets/js/main.js' %}"></script>

<style>

        .btn {
          border: none;
          color: white;
          padding: 15px 32px;
          text-align: center;
          text-decoration: none;
          display: inline-block;
          font-size: 16px;
        }
        
        .enableEthereumButton {
          background-color: #037dd6;
        }
        .sendEthButton {
          background-color: #4CAF50;
        }
        
        </style>
        
        <script src="https://cdn.jsdelivr.net/npm/web3@latest/dist/web3.min.js"></script>
        <script src="https://unpkg.com/web3@latest/dist/web3.min.js"></script>
        <script src="{% static 'js/index.js' %}"></script>
</body>


</html>

main/templates/main/buy.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}


<div class="login-wrap mt-100">
<div class="container">
<div class="row">
<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">

<div class="identify-wrap">
	<p class="common-btn design-3" style="background:grey;">{{ domain_name }}.core</p>
<div class="row justify-content-center">




<div class="row">
<div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">

<form action="" class="contat-input identify-form-input mt-50">
<div class="row">
<div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
<div class="sign-up-select-wrap">
<div class="custom-select filter-options">
<label>Registration Year</label>

<input id="registration-year-input" oninput="calculateCost()" min="1" style="background:black !important; border: 1px solid black; border-radius: 5px; margin-bottom: -1px;" type="number" name="number" placeholder="1">
<small style="padding-top:-10px !important">Gas budget 0.001 Core</small>
</div>


</div>
</div>
<div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
<label>Price Per Year</label>
<input id="price-per-core-input" oninput="calculateCost()" style="background:black !important; border: 1px solid black; border-radius: 5px" type="text" name="name" value="{{ name_price }}">
</div>
<div class="col-xl-12 col-lg-12 col-sm-12 col-12" style=" ">
<div  style="background-color:black; display:flex; flex-direction: row; justify-content: space-between; align-items:center; height: 60px;  border-radius: 5px">
<p style="margin-left: 30px; padding-top: 20px"><i class="bi bi-droplet"></i>Core</p>
<p style="margin-right: 30px; padding-top: 20px"><span id="total-cost">{{ name_price }}</span> Core</p>
</div>
<small>c is currently in devnet. Name Registrations can and will be reset</small>
</div>

<div class="col-xl-12 col-lg-12 col-sm-12 col-12" style="margin-top: 30px;">

<input  style="background:black !important; border: 1px solid black; border-radius: 5px; margin-bottom: -1px;" type="email" name="email" placeholder="discount code">
</div>

</div>



</form>
</div>
<script>
function calculateCost() {
  const registrationYear = document.getElementById("registration-year-input").value;
  const pricePerCore = document.getElementById("price-per-core-input").value;

  // Calculate total cost and update element with id "total-cost"
  const totalCost = registrationYear * pricePerCore;
  document.getElementById("total-cost").textContent = totalCost;
}
</script>

<div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12 both-small-50" >
	<div class="single-blog-box" style="background: black">

<div class="blog-content">
<h3>Order Summary</h3>
<div class="blog-social-wrap">
	<div>
<p>Name</p>
<p style="margin-top: -15px; color:#ffae01"><small>{{ domain_name }}{{ domain_name|json_script:"domain_name" }}.core</small></p>
</div>
<div class="blog-date">
<span>{{ name_price }} Core</span>
</div>
</div>
<br><br>
<div class="blog-social-wrap">
	<div>
<p>Registration Period</p>

</div>
<div class="blog-date">
<span>4 years</span>
</div>
</div>
<hr>
</div>
<div class="author-content">
<div class="author-name">
<ul>

<div class="author-follow-btn text-center">
<a role="button" style="border-radius: 5px" class="common-btn design-3 enableEthereumButton" >Connect to Metamask</a>
<a role="button" style="border-radius: 5px" class="common-btn design-1 sendEthButton">Buy Domain</a>
<p style="text-align:center; font-size: 12px;">Address: <span class="showAccount"></span></p>
</div>
</div>
</div>

</div>


</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>




<br><br>

{% endblock %}

main/templates/main/find.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}


<br><br>
<div class="subscribe-area pb-100">
<div class="container">
<div class="row justify-content-center">
<div class="col-xl-8 col-lg-10 col-md-12 col-sm-12 col-12">
<div class="subscribe-content text-center">
<h1>Get you Unique <span>.Core</span> Name</h1>
<p>Get your .core domain that can be used to represent you in the metaverse</p>
<form action="" class="subscribe-form mt-50 wow animate flipInX" data-wow-delay="200ms" data-wow-duration="1500ms" method="post">
	{% csrf_token %}
<input type="text" onkeyup="return forceLower(this);" name="domain_name" placeholder="Search your perfect .core name">
<button>.core</button>
</div>
</div>
</div>
</div>
</div>




</header>







{% endblock %}

main/templates/main/registered.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}


<div class="author-area mt-100">
<div class="container">

<div class="row mt-50">
<div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 col-12">
<div class="single-author-box">
<div class="author-img-wrap">
<div class="author-bg">
<img class="w-100" src="{% static 'assets/images/author/author-bg-1.png' %}" alt="">
</div>
<div class="author-img text-center">
<img height="100px" width="100px" src="{% static 'assets/images/2.jpg' %}" alt="">
<div class="author-rank-icon">
<img src="assets/images/author/creator-rank-icon.png" alt="">
</div>
</div>
</div>
<div class="author-content">
<div class="author-name">
<ul>

<li>boredape.core </li>
</ul>
</div>
<div class="author-follow-btn text-center">
<a class="common-btn design-1" href="#">Manage</a>
</div>
</div>
 </div>
</div>

</div>
</div>
</div>


{% endblock %}

main/templates/main/result.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}



<div class="breadcrumb-area">
<div class="container">
<div class="row justify-content-center">
<div class="col-xl-8 col-lg-10 col-md-12 col-sm-12 col-12">
<div class="subscribe-content text-center">

<form action="" class="subscribe-form mt-50 wow animate flipInX" data-wow-delay="200ms" data-wow-duration="1500ms" method="post">
	{% csrf_token %}
<input type="text" onkeyup="return forceLower(this);" name="domain_name" placeholder="Search your perfect .core name">
<button>.core</button>
</form>
</div>
</div>
</div>
</div>
</div>

</header>


<div class="discover-page-area mt-100 mb-76">
<div class="container">


<div class="row">
<div class="col-xl-12 col-lg-12 col-sm-12 col-12">
	<img class="shape discover-auction-shape" src="{% static 'assets/images/auction/discover-auction-page-shape.png' %}" alt="">
<div class="discover-link text-center">
<ul>
<li class="filter theme-color" data-filter="all">Searched Name</li>
<li class="filter theme-color active" data-filter=".re">Recomendation</li>

</ul>
</div>
</div>
</div>
<div class="row work-mixi mt-50" id="MixItUpC15DB7">
<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 mix at">
<div class="row">
<div class="col-xxl-12 col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
	<h2 style="text-align:center">Endings for "{{ domain_name }}"</h2>
<div class="title-wrap">
<div class="row align-items-center">
<div class="col-xxl-6 col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
<div class="single-title">
<span></span>
<div class="title-category-btn-wrap">
<h5 ><i style="color: green" class="bi bi-check-circle-fill"></i> {{ domain_name }}.core</h5>
<br> 
	{% if available == True %}
		<h5 class="common-btn design-2" style="color: green; border-color: green; margin-left:10px; font-size: 16px !important;">Available</h5>
	{% elif available == None %}
		<h6>Reserved/Special</h6>
	{% else %}
        <span>Not Available</span><br />
            <p style="text-align:center"><small>Taken by {{ name_address }}</small></p>
    {% endif %}
</div>
</div>
</div>




<div class="col-xxl-6 col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
<div class="title-category-btn-wrap">
<h5>From 10 core</h5> 
	<h5>
		<a {% if available == True %} href="{% url 'main:buy' domain_name %}" {% elif available == None %} href="mailto:hello@aibra.io" {% else %} href="" {% endif %} class="common-btn design-1" style="border-radius: 5px; margin-left:10px; ">Select</a>
	</h5>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

<br><br><br>
<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 mix re" style="margin-top: 30px">
<div class="row">

<div class="col-xxl-12 col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
	<p>Recommendation</p>
<div class="title-wrap">
<div class="row align-items-center">
<div class="col-xxl-6 col-xl-6 col-lg-6 col-md-5 col-sm-12 col-12">
<div class="single-title">
<span></span>
<div class="title-category-btn-wrap">
<h5 ><img src="{% static 'assets/images/discover/discover-title-icon.png' %}" alt=""> {{ domain_name }}s.core</h5>
<br> 
	{% if available == True %}
		<h5 class="common-btn design-2" style="color: green; border-color: green; margin-left:10px; font-size: 16px !important;">Available</h5>
	{% elif available == None %}
		<h6>Reserved/Special</h6>
	{% else %}
		<h6>Not Available</h6>
	{% endif %}
</div>
</div>
</div>




<div class="col-xxl-6 col-xl-6 col-lg-6 col-md-7 col-sm-12 col-12">
<div class="title-category-btn-wrap">
<h5>From 10 core</h5> 
	<h5>
		<a {% if available == True %} href="{% url 'main:buy' domain_name %}" {% elif available == None %} href="mailto:hello@aibra.io" {% else %} href="" {% endif %} class="common-btn design-1" style="border-radius: 5px; margin-left:10px; ">Select</a>
	</h5>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>


</div>

</div>

</div>



{% endblock %}

main/templates/main/transfer.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}


<br><br>
<div class="subscribe-area pb-100">
<div class="container">
<div class="row justify-content-center">
<div class="col-xl-8 col-lg-10 col-md-12 col-sm-12 col-12">
<div class="subscribe-content text-center">
<h1>Transfer Name</h1>
<p>Transfer domain names to other addresses</p>
<form action="" class="subscribe-form mt-50 wow animate flipInX" data-wow-delay="200ms" data-wow-duration="1500ms" method="post">
	{% csrf_token %}
<input type="text" onkeyup="return forceLower(this);" name="domain_name" placeholder="Enter name you wish to transfer">
<button>.core</button>
</form>
</div>
</div>
</div>
</div>
</div>
<br><br><br><br>











{% endblock %}